const express = require('express')
const router = express.router()
const bcrypt = require('bcryptjs')
const jwt = require('jsonwebtoken')
const AuthDB = require('./auth-model.js')
const restrictedMid = require('./restricted.js')